name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt'
        

    - name: Cache SBT
      uses: actions/cache@v3
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      
    - name: Compile code
      run: sbt compile
      
    - name: Run tests
      run: sbt test
