name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - name: Clean targets
      run: sbt clean  
      
    - name: Compile code
      run: sbt compile
      
    - name: Run tests
      run: sbt test
